import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Sidebar from "@/components/dashboard/Sidebar";
import Navbar from "@/components/dashboard/Navbar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} bg-slate-100 pt-[8vh] relative`}>
          <Navbar />
          <nav className="relative md:pl-[55px] lg:pl-[250px]">
            <Sidebar />
            <main className="p-4">{children}</main>
          </nav>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
